# Write your MySQL query statement below
SELECT NAME AS Customers
FROM(
  SELECT NAME, CUSTOMERID
  FROM CUSTOMERS
  LEFT JOIN ORDERS
  ON CUSTOMERS.ID = ORDERS.CUSTOMERID
) AS A
WHERE CUSTOMERID IS NULL

